// Common English words dictionary for validation
const ENGLISH_WORDS = new Set([
  // Pronouns
  "i", "me", "my", "myself", "we", "our", "ours", "ourselves", "you", "your", "yours",
  "yourself", "yourselves", "he", "him", "his", "himself", "she", "her", "hers", "herself",
  "it", "its", "itself", "they", "them", "their", "theirs", "themselves", "what", "which",
  "who", "whom", "this", "that", "these", "those",

  // Common verbs
  "am", "is", "are", "was", "were", "be", "been", "being", "have", "has", "had", "having",
  "do", "does", "did", "doing", "would", "should", "could", "ought", "might", "shall",
  "will", "can", "need", "dare", "may", "must", "go", "going", "gone", "went", "get",
  "gets", "got", "getting", "make", "makes", "made", "making", "know", "knows", "knew",
  "known", "knowing", "think", "thinks", "thought", "thinking", "take", "takes", "took",
  "taken", "taking", "see", "sees", "saw", "seen", "seeing", "come", "comes", "came",
  "coming", "want", "wants", "wanted", "wanting", "look", "looks", "looked", "looking",
  "use", "uses", "used", "using", "find", "finds", "found", "finding", "give", "gives",
  "gave", "given", "giving", "tell", "tells", "told", "telling", "work", "works", "worked",
  "working", "call", "calls", "called", "calling", "try", "tries", "tried", "trying",
  "ask", "asks", "asked", "asking", "put", "puts", "putting", "keep", "keeps", "kept",
  "keeping", "let", "lets", "letting", "begin", "begins", "began", "begun", "beginning",
  "seem", "seems", "seemed", "seeming", "help", "helps", "helped", "helping", "show",
  "shows", "showed", "shown", "showing", "hear", "hears", "heard", "hearing", "play",
  "plays", "played", "playing", "run", "runs", "ran", "running", "move", "moves", "moved",
  "moving", "live", "lives", "lived", "living", "believe", "believes", "believed", "believing",
  "bring", "brings", "brought", "bringing", "happen", "happens", "happened", "happening",
  "write", "writes", "wrote", "written", "writing", "provide", "provides", "provided",
  "sit", "sits", "sat", "sitting", "stand", "stands", "stood", "standing", "lose", "loses",
  "lost", "losing", "pay", "pays", "paid", "paying", "meet", "meets", "met", "meeting",
  "include", "includes", "included", "including", "continue", "continues", "continued",
  "set", "sets", "setting", "learn", "learns", "learned", "learning", "change", "changes",
  "changed", "changing", "lead", "leads", "led", "leading", "understand", "understands",
  "understood", "understanding", "watch", "watches", "watched", "watching", "follow",
  "follows", "followed", "following", "stop", "stops", "stopped", "stopping", "create",
  "creates", "created", "creating", "speak", "speaks", "spoke", "spoken", "speaking",
  "read", "reads", "reading", "allow", "allows", "allowed", "allowing", "add", "adds",
  "added", "adding", "spend", "spends", "spent", "spending", "grow", "grows", "grew",
  "grown", "growing", "open", "opens", "opened", "opening", "walk", "walks", "walked",
  "walking", "win", "wins", "won", "winning", "offer", "offers", "offered", "offering",
  "remember", "remembers", "remembered", "remembering", "love", "loves", "loved", "loving",
  "consider", "considers", "considered", "considering", "appear", "appears", "appeared",
  "appearing", "buy", "buys", "bought", "buying", "wait", "waits", "waited", "waiting",
  "serve", "serves", "served", "serving", "die", "dies", "died", "dying", "send", "sends",
  "sent", "sending", "expect", "expects", "expected", "expecting", "build", "builds",
  "built", "building", "stay", "stays", "stayed", "staying", "fall", "falls", "fell",
  "fallen", "falling", "cut", "cuts", "cutting", "reach", "reaches", "reached", "reaching",
  "kill", "kills", "killed", "killing", "remain", "remains", "remained", "remaining",
  "suggest", "suggests", "suggested", "suggesting", "raise", "raises", "raised", "raising",
  "pass", "passes", "passed", "passing", "sell", "sells", "sold", "selling", "require",
  "requires", "required", "requiring", "report", "reports", "reported", "reporting",
  "decide", "decides", "decided", "deciding", "pull", "pulls", "pulled", "pulling",
  "eat", "eats", "ate", "eaten", "eating", "drink", "drinks", "drank", "drunk", "drinking",
  "sleep", "sleeps", "slept", "sleeping", "wake", "wakes", "woke", "woken", "waking",
  "cry", "cries", "cried", "crying", "laugh", "laughs", "laughed", "laughing",
  "smile", "smiles", "smiled", "smiling", "sing", "sings", "sang", "sung", "singing",
  "dance", "dances", "danced", "dancing", "fight", "fights", "fought", "fighting",
  "hold", "holds", "held", "holding", "wear", "wears", "wore", "worn", "wearing",
  "drive", "drives", "drove", "driven", "driving", "break", "breaks", "broke", "broken",
  "breaking", "wish", "wishes", "wished", "wishing", "miss", "misses", "missed", "missing",
  "hate", "hates", "hated", "hating", "hurt", "hurts", "hurting", "heal", "heals", "healed",
  "healing", "rest", "rests", "rested", "resting", "worry", "worries", "worried", "worrying",
  "care", "cares", "cared", "caring", "feel", "feels", "felt", "feeling", "feelings",
  "exist", "exists", "existed", "existing", "matter", "matters", "mattered", "mattering",
  "succeed", "succeeds", "succeeded", "fail", "fails", "failed", "failing",
  "start", "starts", "started", "starting", "finish", "finishes", "finished", "finishing",
  "enjoy", "enjoys", "enjoyed", "enjoying", "suffer", "suffers", "suffered", "suffering",
  "survive", "survives", "survived", "surviving", "manage", "manages", "managed", "managing",
  "handle", "handles", "handled", "handling", "support", "supports", "supported", "supporting",
  "pray", "prays", "prayed", "praying", "hope", "hopes", "hoped", "hoping",
  "dream", "dreams", "dreamed", "dreaming", "imagine", "imagines", "imagined", "imagining",
  "trust", "trusts", "trusted", "trusting", "doubt", "doubts", "doubted", "doubting",
  "fear", "fears", "feared", "fearing", "accept", "accepts", "accepted", "accepting",
  "deny", "denies", "denied", "denying", "agree", "agrees", "agreed", "agreeing",
  "refuse", "refuses", "refused", "refusing", "apologize", "apologizes", "apologized",
  "forgive", "forgives", "forgave", "forgiven", "forgiving", "promise", "promises", "promised",
  "blame", "blames", "blamed", "blaming", "ignore", "ignores", "ignored", "ignoring",
  "notice", "notices", "noticed", "noticing", "realize", "realizes", "realized", "realizing",
  "recognize", "recognizes", "recognized", "scream", "screams", "screamed", "screaming",
  "shout", "shouts", "shouted", "shouting", "whisper", "whispers", "whispered", "whispering",
  "talk", "talks", "talked", "talking", "say", "says", "said", "saying",
  "explain", "explains", "explained", "explaining", "describe", "describes", "described",
  "complain", "complains", "complained", "complaining", "argue", "argues", "argued", "arguing",
  "discuss", "discusses", "discussed", "discussing", "share", "shares", "shared", "sharing",
  "thank", "thanks", "thanked", "thanking", "celebrate", "celebrates", "celebrated",
  "relax", "relaxes", "relaxed", "relaxing", "breathe", "breathes", "breathed", "breathing",
  "exercise", "exercises", "exercised", "exercising", "cook", "cooks", "cooked", "cooking",
  "clean", "cleans", "cleaned", "cleaning", "fix", "fixes", "fixed", "fixing",
  "travel", "travels", "traveled", "traveling", "visit", "visits", "visited", "visiting",
  "study", "studies", "studied", "studying", "teach", "teaches", "taught", "teaching",
  "practice", "practices", "practiced", "practicing",

  // Feelings & emotions
  "happy", "sad", "angry", "mad", "upset", "anxious", "nervous", "stressed", "depressed",
  "lonely", "alone", "scared", "afraid", "terrified", "worried", "confused", "frustrated",
  "annoyed", "irritated", "bored", "tired", "exhausted", "sick", "ill", "fine", "okay",
  "good", "great", "wonderful", "amazing", "fantastic", "terrible", "horrible", "awful",
  "miserable", "cheerful", "grateful", "thankful", "proud", "ashamed", "embarrassed",
  "guilty", "jealous", "envious", "hopeful", "hopeless", "helpless", "peaceful", "calm",
  "content", "satisfied", "disappointed", "heartbroken", "devastated", "overwhelmed",
  "excited", "thrilled", "delighted", "joyful", "blessed", "lucky", "unlucky", "sorry",
  "regretful", "nostalgic", "melancholy", "gloomy", "numb", "empty", "lost", "stuck",
  "free", "alive", "dead", "broken", "whole", "strong", "weak", "brave", "cowardly",
  "confident", "insecure", "worthy", "worthless", "loved", "unloved", "appreciated",
  "unappreciated", "rejected", "accepted", "abandoned", "betrayed", "hurt", "healed",
  "motivated", "inspired", "determined", "passionate", "indifferent", "apathetic",
  "optimistic", "pessimistic", "positive", "negative", "neutral", "mixed", "complex",
  "intense", "mild", "dumb", "stupid", "smart", "clever", "brilliant", "foolish",
  "crazy", "insane", "sane", "normal", "weird", "strange", "odd", "crazy",
  "furious", "livid", "enraged", "bitter", "resentful", "hostile", "aggressive",
  "gentle", "kind", "cruel", "mean", "nice", "sweet", "lovely", "beautiful",
  "ugly", "pretty", "handsome", "cute", "adorable", "disgusting", "gross",
  "uncomfortable", "comfortable", "restless", "uneasy", "tense", "relaxed",
  "panicked", "shocked", "surprised", "stunned", "amazed", "astonished",
  "speechless", "bewildered", "curious", "interested", "fascinated",
  "distressed", "tormented", "agonized", "suffering", "miserable",

  // Common nouns
  "time", "year", "people", "way", "day", "man", "woman", "child", "children", "world",
  "life", "hand", "part", "place", "case", "week", "company", "system", "program",
  "question", "work", "government", "number", "night", "point", "home", "water", "room",
  "mother", "area", "money", "story", "fact", "month", "lot", "right", "study", "book",
  "eye", "job", "word", "business", "issue", "side", "kind", "head", "house", "service",
  "friend", "father", "power", "hour", "game", "line", "end", "member", "law", "car",
  "city", "community", "name", "president", "team", "minute", "idea", "body", "information",
  "back", "parent", "face", "others", "level", "office", "door", "health", "person",
  "art", "war", "history", "party", "result", "morning", "reason", "research", "girl",
  "guy", "moment", "air", "teacher", "force", "education", "boy", "age", "policy",
  "music", "food", "family", "heart", "mind", "brain", "soul", "spirit", "god",
  "death", "pain", "blood", "baby", "dog", "cat", "animal", "bird", "tree", "flower",
  "sun", "moon", "star", "sky", "rain", "snow", "wind", "fire", "earth", "sea", "ocean",
  "river", "mountain", "road", "street", "school", "college", "university", "hospital",
  "church", "garden", "park", "forest", "island", "beach", "desert", "village", "town",
  "morning", "afternoon", "evening", "tonight", "today", "tomorrow", "yesterday",
  "weekend", "holiday", "birthday", "wedding", "funeral", "accident", "emergency",
  "problem", "solution", "answer", "success", "failure", "mistake", "lesson", "truth",
  "lie", "secret", "mystery", "memory", "dream", "nightmare", "wish", "goal", "plan",
  "future", "past", "present", "beginning", "middle", "ending", "peace", "violence",
  "freedom", "justice", "love", "friendship", "relationship", "marriage", "divorce",
  "trust", "respect", "honor", "dignity", "courage", "fear", "anger", "joy", "sorrow",
  "grief", "loss", "hope", "faith", "doubt", "belief", "prayer", "meditation",
  "therapy", "medicine", "doctor", "nurse", "patient", "disease", "cure", "treatment",
  "recovery", "healing", "strength", "weakness", "energy", "fatigue", "stress", "anxiety",
  "depression", "trauma", "abuse", "neglect", "support", "comfort", "safety", "danger",
  "risk", "challenge", "opportunity", "experience", "adventure", "journey", "path",
  "choice", "decision", "consequence", "responsibility", "duty", "burden", "relief",
  "gratitude", "appreciation", "kindness", "compassion", "empathy", "sympathy",
  "patience", "tolerance", "forgiveness", "guilt", "shame", "pride", "humility",
  "happiness", "sadness", "loneliness", "isolation", "connection", "belonging",
  "purpose", "meaning", "value", "worth", "beauty", "chaos", "order", "balance",
  "harmony", "conflict", "struggle", "victory", "defeat", "survival", "existence",
  "reality", "fantasy", "imagination", "creativity", "intelligence", "wisdom",
  "knowledge", "understanding", "confusion", "clarity", "darkness", "light",
  "silence", "noise", "voice", "sound", "touch", "taste", "smell", "sight",
  "thought", "emotion", "sensation", "intuition", "instinct", "nature", "weather",
  "season", "spring", "summer", "autumn", "winter", "color", "shape", "size",
  "distance", "space", "universe", "nothing", "everything", "something", "anything",
  "someone", "everyone", "nobody", "anybody", "somewhere", "everywhere", "nowhere",
  "brother", "sister", "son", "daughter", "husband", "wife", "partner", "boyfriend",
  "girlfriend", "boss", "colleague", "neighbor", "stranger", "enemy", "hero",
  "victim", "survivor", "leader", "follower", "mentor", "student",
  "exam", "test", "class", "grade", "score", "performance", "progress", "improvement",
  "effort", "attention", "focus", "concentration", "distraction", "interruption",
  "rest", "sleep", "nap", "meal", "breakfast", "lunch", "dinner", "snack",
  "coffee", "tea", "milk", "juice", "beer", "wine", "alcohol", "drug", "smoke",
  "habit", "routine", "schedule", "calendar", "clock", "alarm", "deadline",
  "pressure", "tension", "release", "escape", "vacation", "trip", "flight",

  // Articles, prepositions, conjunctions
  "a", "an", "the", "and", "but", "or", "nor", "for", "yet", "so", "at", "by", "in",
  "of", "on", "to", "up", "as", "if", "no", "not", "all", "any", "few", "how",
  "its", "let", "may", "new", "now", "old", "own", "say", "too", "why", "about",
  "above", "after", "again", "also", "away", "back", "been", "before", "being",
  "below", "between", "both", "down", "during", "each", "even", "every", "first",
  "from", "here", "into", "just", "last", "like", "long", "many", "more", "most",
  "much", "never", "next", "only", "other", "over", "same", "some", "such", "than",
  "then", "there", "through", "under", "very", "well", "where", "while", "with",
  "without", "within", "upon", "along", "among", "around", "because", "before",
  "behind", "beside", "besides", "beyond", "since", "still", "though", "unless",
  "until", "whether", "already", "always", "another", "anyway", "anywhere",
  "against", "across", "toward", "towards", "outside", "inside", "instead",
  "together", "apart", "alone", "enough", "quite", "rather", "almost", "really",
  "actually", "probably", "perhaps", "maybe", "definitely", "certainly", "absolutely",
  "completely", "totally", "entirely", "exactly", "hardly", "barely", "nearly",
  "simply", "truly", "finally", "suddenly", "quickly", "slowly", "carefully",
  "seriously", "honestly", "literally", "basically", "especially", "particularly",
  "recently", "currently", "eventually", "immediately", "constantly", "frequently",
  "usually", "sometimes", "often", "rarely", "seldom", "once", "twice",

  // Common adjectives
  "big", "small", "large", "little", "young", "old", "new", "long", "short",
  "high", "low", "good", "bad", "best", "worst", "better", "worse", "right", "wrong",
  "true", "false", "real", "fake", "hard", "soft", "easy", "difficult", "simple",
  "possible", "impossible", "important", "necessary", "different", "similar", "same",
  "special", "general", "common", "rare", "popular", "famous", "known", "unknown",
  "clear", "obvious", "certain", "sure", "ready", "able", "unable", "available",
  "open", "close", "closed", "full", "empty", "rich", "poor", "expensive", "cheap",
  "fast", "slow", "quick", "early", "late", "hot", "cold", "warm", "cool", "wet", "dry",
  "clean", "dirty", "dark", "bright", "deep", "shallow", "wide", "narrow", "thick", "thin",
  "heavy", "light", "loud", "quiet", "rough", "smooth", "sharp", "dull", "fresh", "stale",
  "safe", "dangerous", "healthy", "unhealthy", "fair", "unfair", "honest", "dishonest",
  "serious", "funny", "silly", "boring", "interesting", "exciting", "wonderful",
  "perfect", "terrible", "horrible", "awful", "amazing", "incredible", "unbelievable",
  "crazy", "wild", "strange", "normal", "usual", "unusual", "natural", "artificial",

  // Greetings & common expressions
  "hi", "hello", "hey", "bye", "goodbye", "please", "thanks", "welcome", "sorry",
  "yes", "no", "yeah", "yep", "nah", "nope", "ok", "okay", "alright", "sure", "wow",
  "oh", "oops", "ugh", "hmm", "huh", "yay", "ouch", "ow", "ah", "aha",

  // Additional common words
  "thing", "stuff", "lot", "bit", "piece", "type", "form", "group", "set",
  "number", "order", "point", "turn", "change", "move", "step", "stage", "state",
  "level", "class", "act", "fact", "case", "cause", "effect", "result", "end",
  "means", "sense", "term", "sign", "mark", "note", "view", "role", "rule",
  "base", "rate", "range", "deal", "need", "example", "model", "reason",
  "figure", "record", "period", "society", "land", "market", "process",
  "field", "practice", "century", "development", "control", "share",
  "course", "position", "approach", "condition", "situation", "activity",
  "experience", "interest", "concern", "material", "particular", "culture",
  "individual", "evidence", "feature", "property", "quality", "whole",
  "single", "standard", "natural", "significant", "similar", "current",
  "common", "specific", "final", "main", "central", "potential", "powerful",
  "personal", "private", "public", "social", "political", "economic", "financial",
  "physical", "mental", "emotional", "spiritual", "professional", "academic",
  "technical", "medical", "legal", "military", "religious", "cultural",
  "traditional", "modern", "ancient", "recent", "previous", "following",
  "original", "additional", "basic", "essential", "critical", "vital",
  "major", "minor", "primary", "secondary", "local", "national", "international",
  "global", "human", "divine", "male", "female", "adult",

  // Contractions (without apostrophe for matching)
  "dont", "didnt", "doesnt", "cant", "wont", "shouldnt", "wouldnt", "couldnt",
  "isnt", "arent", "wasnt", "werent", "hasnt", "havent", "hadnt", "im", "ive",
  "ill", "youre", "youve", "youll", "hes", "shes", "theyre", "theyve", "theyll",
  "weve", "were", "lets", "thats", "whats", "whos", "hows", "whys", "theres",
]);

export function isEnglishWord(word: string): boolean {
  // Strip punctuation and lowercase
  const clean = word.toLowerCase().replace(/[^a-z']/g, '').replace(/'/g, '');
  if (clean.length === 0) return false;
  if (ENGLISH_WORDS.has(clean)) return true;

  // Check common suffixes: -ing, -ed, -ly, -er, -est, -tion, -ness, -ment, -ful, -less, -able, -ible, -ous, -ive, -al, -en, -ize, -ise, -ify
  const suffixes = ['ing', 'ed', 'ly', 'er', 'est', 'tion', 'sion', 'ness', 'ment', 'ful', 'less', 'able', 'ible', 'ous', 'ive', 'al', 'en', 'ize', 'ise', 'ify', 'ity', 'ence', 'ance', 's', 'es'];
  for (const suffix of suffixes) {
    if (clean.endsWith(suffix)) {
      const root = clean.slice(0, -suffix.length);
      if (root.length >= 2 && ENGLISH_WORDS.has(root)) return true;
      // Try adding back 'e' (e.g., "loving" -> "lov" + "e" = "love")
      if (root.length >= 2 && ENGLISH_WORDS.has(root + 'e')) return true;
    }
  }

  return false;
}
