project_id = "mhmhgnkuburefllvnirp"

[functions.send-login-alert]
verify_jwt = false

[functions.send-notifications]
verify_jwt = false

[functions.analyze-emotion]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false
